#
#
#

srcdir	= ../../Document/KiwiControls/KCGraphics

all: clean
	(cd $(srcdir) ; tar cf - *) | tar xfv -

clean:
	rm -rf Classes* Functions* Extensions* Structs* 
	rm -rf css docsets img index.html undocumented.json

dummy:


